### ISSUE TITLE
Unable to connect to kaizoku

### ISSUE THREAD

**Issue by sosudaniel** [oae/kaizoku#142]
### Describe the bug

Hello everyone. Using the same configuration that i have been used from the start. some time yesterday, without any changes to docker compose file Kaizoku does not start anymore.

logs: 
✓ set downloader.download_cover to true
✓ set downloader.redownload_existing to true
✓ set downloader.chapter_name_template to [{padded-index}] {chapter}
✓ set downloader.create_manga_dir to true
✓ set downloader.create_volume_dir to false
✓ set downloader.stop_on_error to true
✓ set downloader.path to .
prisma:error 
Invalid `prisma.manga.findMany()` invocation:
Can't reach database server at `db`:`5432`
Please make sure your database server is running at `db`:`5432`.
[22:40:44.188] ERROR (28266): 
Invalid `prisma.manga.findMany()` invocation:
Can't reach database server at `db`:`5432`
Please make sure your database server is running at `db`:`5432`.
    err: {
      "type": "PrismaClientInitializationError",
      "message": "\nInvalid `prisma.manga.findMany()` invocation:\n\n\nCan't reach database server at `db`:`5432`\n\nPlease make sure your database server is running at `db`:`5432`.",
      "stack":
          Error: 
          Invalid `prisma.manga.findMany()` invocation:
          
          
          Can't reach database server at `db`:`5432`
          
          Please make sure your database server is running at `db`:`5432`.
              at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:31955:13)
              at RequestHandler.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:31913:12)
              at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:31908:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:32994:16)
      "clientVersion": "4.9.0"
    }
✓ set metadata.comic_info_xml to true
✓ set metadata.fetch_anilist to true
✓ set metadata.series_json to true
✓ set formats.use to cbz
✓ set downloader.download_cover to true
✓ set downloader.redownload_existing to true
✓ set downloader.chapter_name_template to [{padded-index}] {chapter}
✓ set downloader.create_manga_dir to true
✓ set downloader.create_volume_dir to false
✓ set downloader.stop_on_error to true
✓ set downloader.path to .
prisma:error 
Invalid `prisma.manga.findMany()` invocation:
Can't reach database server at `db`:`5432`
Please make sure your database server is running at `db`:`5432`.
[22:40:47.594] ERROR (28383): 
Invalid `prisma.manga.findMany()` invocation:
Can't reach database server at `db`:`5432`
Please make sure your database server is running at `db`:`5432`.
    err: {
      "type": "PrismaClientInitializationError",
      "message": "\nInvalid `prisma.manga.findMany()` invocation:\n\n\nCan't reach database server at `db`:`5432`\n\nPlease make sure your database server is running at `db`:`5432`.",
      "stack":
          Error: 
          Invalid `prisma.manga.findMany()` invocation:
          
          
          Can't reach database server at `db`:`5432`
          
          Please make sure your database server is running at `db`:`5432`.
              at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:31955:13)
              at RequestHandler.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:31913:12)
              at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:31908:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client/runtime/index.js:32994:16)
      "clientVersion": "4.9.0"
    }
✓ set metadata.comic_info_xml to true
✓ set metadata.fetch_anilist to true
✓ set metadata.series_json to true
✓ set formats.use to cbz
✓ set downloader.download_cover to true
✓ set downloader.redownload_existing to true
✓ set downloader.chapter_name_template to [{padded-index}] {chapter}
✓ set downloader.create_manga_dir to true
✓ set downloader.create_volume_dir to false
✓ set downloader.stop_on_error to true
✓ set downloader.path to .
prisma:error 
Invalid `prisma.manga.findMany()` invocation:
Can't reach database server at `db`:`5432`
Please make sure your database server is running at `db`:`5432`.

docker-compose snip:
app:
    image: ghcr.io/oae/kaizoku
    container_name: kaizoku
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Bucharest
      - PGID=1000
      - PUID=1000
    volumes:
      - /whatever/manga_data/manga:/data
      - /whatever/config_kaizou/config:/config
      - /whatever/config_kaizou/logs:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '10013:3000'
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_alpine
    volumes:
      - redis:/data
    restart: unless-stopped
  
  db:
    image: postgres:alpine
    container_name: postgress_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizokuPass
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

### Reproduction steps

Use compose file mentioned in the description triggers an error that does not allow to connect to Kaizoku.

### Expected behavior

Connection to Kaizoku should be available.

**Comment by sosudaniel** [comment]
Solved with usage of 15-alpine version for postgres
image: postgres:15-alpine

**Comment by sosudaniel** [comment]
Might be worth to update the https://github.com/oae/kaizoku#deployment tab
