### ISSUE TITLE
Strange error on some chapters

### ISSUE THREAD

**Issue by Typhonragewind** [oae/kaizoku#31]
### Describe the bug

I've been using the software for a few days and congrats! It's great and has a great interface, it's exactly what i was looking for.

However, out of almost 12k chapters i've been getting some strange errors on about 200 of them. Here's a log excerpt from Bull Dashboard, in case you wanna take a look at it:

```
Error: Command failed with exit code 2: mangal inline --source Manganelo --query Black Clover --manga first --chapters 347 -d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5037e2]

goroutine 1 [running]:
bytes.(*Buffer).WriteTo(0x153e820?, {0x153e820?, 0xc0000ae500?})
	bytes/buffer.go:250 +0x22
io.copyBuffer({0x153e820, 0xc0000ae500}, {0x153e8c0, 0x0}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x16e
io.Copy(...)
	io/io.go:386
github.com/metafates/mangal/converter/cbz.addToZip(0xc0003f3340?, {0x153e8c0, 0x0}, {0xc0007adec0, 0xa})
	github.com/metafates/mangal/converter/cbz/cbz.go:83 +0xa6
github.com/metafates/mangal/converter/cbz.SaveTo(0xc00066c700, {0xc0002cbf50?, 0xc0001c9150?})
	github.com/metafates/mangal/converter/cbz/cbz.go:55 +0x36b
github.com/metafates/mangal/converter/cbz.save(0xe5bd00?, 0x1?)
	github.com/metafates/mangal/converter/cbz/cbz.go:35 +0x3f
github.com/metafates/mangal/converter/cbz.(*CBZ).Save(0xc0007ada50, 0xe?)
	github.com/metafates/mangal/converter/cbz/cbz.go:22 +0x1e
github.com/metafates/mangal/downloader.Download(0xc00066c700, 0x12daa30)
	github.com/metafates/mangal/downloader/download.go:104 +0xbe7
github.com/metafates/mangal/inline.Run(0xc0008e7c88)
	github.com/metafates/mangal/inline/inline.go:96 +0x4eb
github.com/metafates/mangal/cmd.glob..func11(0x1cf7b60?, {0x10068d7?, 0x9?, 0x9?})
	github.com/metafates/mangal/cmd/inline.go:147 +0x525
github.com/spf13/cobra.(*Command).execute(0x1cf7b60, {0xc0001a8900, 0x9, 0x9})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1cfaf20)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/metafates/mangal/cmd.Execute()
	github.com/metafates/mangal/cmd/root.go:109 +0x5e
main.main()
	github.com/metafates/mangal/main.go:13 +0x4d
    at makeError (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadChapter (/app/.next/server/pages/api/trpc/[trpc].js:1310:48)
    at async external_bullmq_.Worker.concurrency [as processFn] (/app/.next/server/pages/api/trpc/[trpc].js:432:20)
    at async Worker.processJob (/app/node_modules/.pnpm/bullmq@3.1.2/node_modules/bullmq/dist/cjs/classes/worker.js:343:28)
    at async Worker.retryIfFailed (/app/node_modules/.pnpm/bullmq@3.1.2/node_modules/bullmq/dist/cjs/classes/worker.js:465:24)
Error: Command failed with exit code 2: mangal inline --source Manganelo --query Black Clover --manga first --chapters 347 -d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5037e2]

goroutine 1 [running]:
bytes.(*Buffer).WriteTo(0x153e820?, {0x153e820?, 0xc0001187d0?})
	bytes/buffer.go:250 +0x22
io.copyBuffer({0x153e820, 0xc0001187d0}, {0x153e8c0, 0x0}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x16e
io.Copy(...)
	io/io.go:386
github.com/metafates/mangal/converter/cbz.addToZip(0xc0000a7800?, {0x153e8c0, 0x0}, {0xc000636840, 0xa})
	github.com/metafates/mangal/converter/cbz/cbz.go:83 +0xa6
github.com/metafates/mangal/converter/cbz.SaveTo(0xc0003ac600, {0xc0005bb6b0?, 0xc0006275f0?})
	github.com/metafates/mangal/converter/cbz/cbz.go:55 +0x36b
github.com/metafates/mangal/converter/cbz.save(0xe5bd00?, 0x1?)
	github.com/metafates/mangal/converter/cbz/cbz.go:35 +0x3f
github.com/metafates/mangal/converter/cbz.(*CBZ).Save(0xc0006363d0, 0xe?)
	github.com/metafates/mangal/converter/cbz/cbz.go:22 +0x1e
github.com/metafates/mangal/downloader.Download(0xc0003ac600, 0x12daa30)
	github.com/metafates/mangal/downloader/download.go:104 +0xbe7
github.com/metafates/mangal/inline.Run(0xc0004b5c88)
	github.com/metafates/mangal/inline/inline.go:96 +0x4eb
github.com/metafates/mangal/cmd.glob..func11(0x1cf7b60?, {0x10068d7?, 0x9?, 0x9?})
	github.com/metafates/mangal/cmd/inline.go:147 +0x525
github.com/spf13/cobra.(*Command).execute(0x1cf7b60, {0xc000186900, 0x9, 0x9})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1cfaf20)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/metafates/mangal/cmd.Execute()
	github.com/metafates/mangal/cmd/root.go:109 +0x5e
main.main()
	github.com/metafates/mangal/main.go:13 +0x4d
    at makeError (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadChapter (/app/.next/server/pages/api/trpc/[trpc].js:1310:48)
    at async external_bullmq_.Worker.concurrency [as processFn] (/app/.next/server/pages/api/trpc/[trpc].js:432:20)
    at async Worker.processJob (/app/node_modules/.pnpm/bullmq@3.1.2/node_modules/bullmq/dist/cjs/classes/worker.js:343:28)
    at async Worker.retryIfFailed (/app/node_modules/.pnpm/bullmq@3.1.2/node_modules/bullmq/dist/cjs/classes/worker.js:465:24)
Error: Command failed with exit code 2: mangal inline --source Manganelo --query Black Clover --manga first --chapters 347 -d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5037e2]

goroutine 1 [running]:
bytes.(*Buffer).WriteTo(0x153e820?, {0x153e820?, 0xc000180fa0?})
	bytes/buffer.go:250 +0x22
io.copyBuffer({0x153e820, 0xc000180fa0}, {0x153e8c0, 0x0}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x16e
io.Copy(...)
	io/io.go:386
github.com/metafates/mangal/converter/cbz.addToZip(0xc00047f2c0?, {0x153e8c0, 0x0}, {0xc00038f0c0, 0xa})
	github.com/metafates/mangal/converter/cbz/cbz.go:83 +0xa6
github.com/metafates/mangal/converter/cbz.SaveTo(0xc000448600, {0xc000514060?, 0xc00047b110?})
	github.com/metafates/mangal/converter/cbz/cbz.go:55 +0x36b
github.com/metafates/mangal/converter/cbz.save(0xe5bd00?, 0x1?)
	github.com/metafates/mangal/converter/cbz/cbz.go:35 +0x3f
github.com/metafates/mangal/converter/cbz.(*CBZ).Save(0xc00038ec00, 0xe?)
	github.com/metafates/mangal/converter/cbz/cbz.go:22 +0x1e
github.com/metafates/mangal/downloader.Download(0xc000448600, 0x12daa30)
	github.com/metafates/mangal/downloader/download.go:104 +0xbe7
github.com/metafates/mangal/inline.Run(0xc0008fdc88)
	github.com/metafates/mangal/inline/inline.go:96 +0x4eb
github.com/metafates/mangal/cmd.glob..func11(0x1cf7b60?, {0x10068d7?, 0x9?, 0x9?})
	github.com/metafates/mangal/cmd/inline.go:147 +0x525
github.com/spf13/cobra.(*Command).execute(0x1cf7b60, {0xc000216900, 0x9, 0x9})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1cfaf20)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/metafates/mangal/cmd.Execute()
	github.com/metafates/mangal/cmd/root.go:109 +0x5e
main.main()
	github.com/metafates/mangal/main.go:13 +0x4d
    at makeError (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by oae** [comment]
I am facing this too. Using mangal, I can reproduce this issue. I have created a new report https://github.com/metafates/mangal/issues/135.
