### ISSUE TITLE
Docker Synology

### ISSUE THREAD

**Issue by xthephreakx** [oae/kaizoku#60]
this is no bug but a help request.

i  ran the composer on my docker hosted on synology via portainer.
3 dockers are created succesfully and are up and running

but somehow i cant connect to the page am i missing something ? or do i need to do something after the dockers are created ?

**Comment by javijuji** [comment]
Ran into the same issue. Seems like the app cant reach db at port 5432. Meanwhile db seems to be running correctly on port 5432 and listening to connections.

2023-01-17 23:07:05.801 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-01-17 23:07:05.801 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-01-17 23:07:05.851 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-01-17 23:07:05.927 UTC [25] LOG:  database system was shut down at 2023-01-17 23:06:41 UTC
2023-01-17 23:07:05.954 UTC [1] LOG:  database system is ready to accept connections

**Comment by oae** [comment]
I am also using docker on Synology. The default network created by docker on Nas cannot resolve service names. Can you create a bridge network and use that?

**Comment by oae** [comment]
Can you try this guide?

https://drfrankenstein.co.uk/step-3-setting-up-a-docker-bridge-network/

**Comment by oae** [comment]
Can you share your exact `docker-compose.yml` file?

**Comment by xthephreakx** [comment]
sure and thnx for the fast replies !

`version: '3'

volumes:
  db:
  redis:

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UID=1038
      - GID=65547
      - TZ=Europe/Amsterdam 
    volumes:
      - /volume1/docker/kaizoku/data:/data:rw
      - /volume1/docker/kaizoku/config:/config:rw
      - /volume1/docker/kaizoku/logs:/logs:rw
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - db:/var/lib/postgresql/data
`

**Comment by xthephreakx** [comment]
Oke another update I noticed in the composer that there are a DB and a REDIS volume declared so I made these folders and added the locations to the composer. 

Only thing that gives errors now in the logs is kaizoku docker

_          Please make sure your database server is running at `db`:`5432`.
          Can't reach database server at `db`:`5432`
[00:01:58.850] ERROR (5542): 
    err: {
      "message": "\nInvalid `prisma.manga.findMany()` invocation:\n\n\nCan't reach database server at `db`:`5432`\n\nPlease make sure your database server is running at `db`:`5432`.",
      "type": "PrismaClientInitializationError",
          Error: 
      "stack":
      "clientVersion": "4.6.1"
          Invalid `prisma.manga.findMany()` invocation:
              at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/@prisma/client/runtime/index.js:34316:13)
              at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/@prisma/client/runtime/index.js:34293:12)
              at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/@prisma/client/runtime/index.js:35273:16)
          
[00:02:34.588] ERROR (5881): 
Please make sure your database server is running at `db`:`5432`.
Can't reach database server at `db`:`5432`
Invalid `prisma.manga.findMany()` invocation:
[00:02:46.191] ERROR (5994): _

**Comment by oae** [comment]
I tried it but I cannot reproduce this.

**Comment by xthephreakx** [comment]
Damn that's unfortunate :(. Fixed another docker which couldn't communicate with my other container which was due to I had multiple gateways enabled on my nas. But it did t fix this issue I'll try it again from scratch after I brought the kids to bed.

**Comment by xthephreakx** [comment]
Well I think fixing my gateway shizzle on the nas and redeploying the stack solved my problem :). 

Thnx for the support. So I guess if anyone else has this issue on a synology nas they have to check if they have this setting set to enable cause that might brake some stuff....

![image](https://user-images.githubusercontent.com/5319954/213819862-ed888f38-a015-4982-9e3f-774a5d5c58f4.jpeg)
